apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app: homepage
data:
  settings.yaml: |
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    cardBlur: md
    theme: dark
    headerStyle: boxed
    hideVersion: true
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
  services.yaml: |
    - Popular:
      - Jellyfin:
          href: https://jellyfin.fabsys.ovh
          description: Media system (movies, music, etc.)
          icon: jellyfin.svg
      - Jellyseerr:
          href: https://jellyseerr.fabsys.ovh
          description: Request media
          icon: jellyseerr.svg
      - Paperless:
          href: https://paperless.fabsys.ovh
          description: Document management system
          icon: paperless.svg
    - Management:
      - Qbittorrent:
          href: http://qbittorrent.services.k8s
          description: Qbittorrent client
          icon: qbittorrent.svg
      - Filebrowser:
          href: http://filebrowser.services.k8s
          description: Filebrowser
          icon: filebrowser.svg
      - Prowlarr:
          href: https://prowlarr.services.k8s
          description: Indexer manager
          icon: prowlarr.svg
      - Radarr:
          href: https://radarr.services.k8s
          description: Movie manager
          icon: radarr.svg
      - Sonarr:
          href: https://sonarr.services.k8s
          description: TV show manager
          icon: sonarr.svg
    - Development:
      - ArgoCD:
          href: https://argocd.services.k8s
          description: Continuous deployment
          icon: argocd.svg
  bookmarks.yaml: |
    - Homelab:
      - Public homelab repository:
        - href: https://github.com/fabsys/k3s-lxc_proxmox/
          icon: github.svg
    - Managed services:
      - Cloudflare:
        - href: https://dash.cloudflare.com
          icon: cloudflare.svg
      - Terraform Cloud:
        - href: https://app.terraform.io
          icon: terraform.svg
    - Infrastructure:
      - Router:
        - href: https://192.168.1.1
          icon: router.svg
      - Proxmox:
        - href: https://pve.lan:8006
          icon: proxmox.svg
      - Google Cloud:
        - href: https://console.cloud.google.com
          icon: google-cloud-platform.svg