resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.18.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.18.0/system-upgrade-controller.yaml
#namespace: cattle-system
